on:
  release:
    types: [created]
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install virtualenv
      run: |
        if [ `id -u` -eq 0 ]; then
          apt-get update
          apt-get install -y virtualenv python2 zip
        else
          sudo apt-get update
          sudo apt-get install -y virtualenv python2 zip
        fi
    - name: Create python3 venv
      run: |
        for _python in 2 3; do
          virtualenv -p python${_python} env${_python}
          if [ "${_python}" -eq 2 ]; then
            ./env${_python}/bin/pip install Appium-Python-Client==0.52
          else
            ./env${_python}/bin/pip install Appium-Python-Client
          fi
          ./env${_python}/bin/pip freeze | grep -v "pkg-resources" | grep -v "pkg_resources" > env${_python}/requirements.txt
          zip sample_env_python${_python}.zip -j env${_python}/requirements.txt
          zip sample_env_python${_python}.zip -r tests
          cp sample_env_python${_python}.zip sample_env_python${_python}_wh.zip
          rm -Rf wheelhouse
          ./env${_python}/bin/pip wheel -r env${_python}/requirements.txt -w wheelhouse
          zip sample_env_python${_python}_wh.zip -r wheelhouse
        done
    - name: Build Android app
      working-directory: ./android
      run: |
        ./gradlew --no-daemon build
        cp build/outputs/apk/debug/android-debug.apk ../fi.aardsoft.devicefarmsample-debug.apk
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          sample_env_python2.zip
          sample_env_python3.zip
          sample_env_python2_wh.zip
          sample_env_python3_wh.zip
          test_spec.yaml
          fi.aardsoft.devicefarmsample-debug.apk
